services:
  - type: web
    name: tg-suggest-bot
    env: python
    plan: free
    pythonVersion: 3.11.8        # ✅ исправление
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMINS
        sync: false
